# Generated by Django 4.2.5 on 2023-10-07 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token_calendar",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_calender", models.CharField(null=True)),
                ("summary", models.CharField(blank=True, max_length=255, null=True)),
                ("detail", models.TextField(null=True)),
                ("start_time", models.DateField(null=True)),
                ("end_time", models.DateField(null=True)),
                ("time_reminder", models.BigIntegerField(blank=True, null=True)),
                ("repeat_time", models.IntegerField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("day", "Day"), ("hour", "Hour"), ("minute", "Minute"), ("second", "Second")],
                        default="hour",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
