# Generated by Django 4.2.5 on 2023-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_calendar_creator_calendar_htmllink_calendar_icaluid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="creator",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="detail",
            field=models.TextField(max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="htmlLink",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="iCalUID",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="location",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="status",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="summary",
            field=models.CharField(blank=True, max_length=12000, null=True),
        ),
    ]
