# Generated by Django 4.2.5 on 2023-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_calendar_creator_alter_calendar_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
