# Generated by Django 4.2.5 on 2023-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_calendar_end_time_alter_calendar_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
